version: "3.8"

services:
  backend:
    build: ./backend
    container_name: mini-blog-backend
    ports:
      - "1111:1111"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: mini-blog-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
